// Code generated by protoc-gen-go. DO NOT EDIT.
// source: CfgPlayerAttr.proto

package dataConfig

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// key:["id"]
type CfgPlayerAttr struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	InitData             int32    `protobuf:"varint,3,opt,name=initData,proto3" json:"initData,omitempty"`
	IncData              int32    `protobuf:"varint,4,opt,name=incData,proto3" json:"incData,omitempty"`
	MaxData              int32    `protobuf:"varint,5,opt,name=maxData,proto3" json:"maxData,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CfgPlayerAttr) Reset()         { *m = CfgPlayerAttr{} }
func (m *CfgPlayerAttr) String() string { return proto.CompactTextString(m) }
func (*CfgPlayerAttr) ProtoMessage()    {}
func (*CfgPlayerAttr) Descriptor() ([]byte, []int) {
	return fileDescriptor_CfgPlayerAttr_e6e2eb8248525846, []int{0}
}
func (m *CfgPlayerAttr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CfgPlayerAttr.Unmarshal(m, b)
}
func (m *CfgPlayerAttr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CfgPlayerAttr.Marshal(b, m, deterministic)
}
func (dst *CfgPlayerAttr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CfgPlayerAttr.Merge(dst, src)
}
func (m *CfgPlayerAttr) XXX_Size() int {
	return xxx_messageInfo_CfgPlayerAttr.Size(m)
}
func (m *CfgPlayerAttr) XXX_DiscardUnknown() {
	xxx_messageInfo_CfgPlayerAttr.DiscardUnknown(m)
}

var xxx_messageInfo_CfgPlayerAttr proto.InternalMessageInfo

func (m *CfgPlayerAttr) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CfgPlayerAttr) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *CfgPlayerAttr) GetInitData() int32 {
	if m != nil {
		return m.InitData
	}
	return 0
}

func (m *CfgPlayerAttr) GetIncData() int32 {
	if m != nil {
		return m.IncData
	}
	return 0
}

func (m *CfgPlayerAttr) GetMaxData() int32 {
	if m != nil {
		return m.MaxData
	}
	return 0
}

type PlayerAttrConfigData struct {
	Config               []*CfgPlayerAttr `protobuf:"bytes,1,rep,name=config,proto3" json:"config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *PlayerAttrConfigData) Reset()         { *m = PlayerAttrConfigData{} }
func (m *PlayerAttrConfigData) String() string { return proto.CompactTextString(m) }
func (*PlayerAttrConfigData) ProtoMessage()    {}
func (*PlayerAttrConfigData) Descriptor() ([]byte, []int) {
	return fileDescriptor_CfgPlayerAttr_e6e2eb8248525846, []int{1}
}
func (m *PlayerAttrConfigData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerAttrConfigData.Unmarshal(m, b)
}
func (m *PlayerAttrConfigData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerAttrConfigData.Marshal(b, m, deterministic)
}
func (dst *PlayerAttrConfigData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerAttrConfigData.Merge(dst, src)
}
func (m *PlayerAttrConfigData) XXX_Size() int {
	return xxx_messageInfo_PlayerAttrConfigData.Size(m)
}
func (m *PlayerAttrConfigData) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerAttrConfigData.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerAttrConfigData proto.InternalMessageInfo

func (m *PlayerAttrConfigData) GetConfig() []*CfgPlayerAttr {
	if m != nil {
		return m.Config
	}
	return nil
}

func init() {
	proto.RegisterType((*CfgPlayerAttr)(nil), "dataConfig.CfgPlayerAttr")
	proto.RegisterType((*PlayerAttrConfigData)(nil), "dataConfig.PlayerAttrConfigData")
}

func init() { proto.RegisterFile("CfgPlayerAttr.proto", fileDescriptor_CfgPlayerAttr_e6e2eb8248525846) }

var fileDescriptor_CfgPlayerAttr_e6e2eb8248525846 = []byte{
	// 178 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x76, 0x4e, 0x4b, 0x0f,
	0xc8, 0x49, 0xac, 0x4c, 0x2d, 0x72, 0x2c, 0x29, 0x29, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0xe2, 0x4a, 0x49, 0x2c, 0x49, 0x74, 0xce, 0xcf, 0x4b, 0xcb, 0x4c, 0x57, 0x6a, 0x64, 0xe4, 0xe2,
	0x45, 0x51, 0x23, 0xc4, 0xc7, 0xc5, 0x94, 0x99, 0x22, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x1a, 0xc4,
	0x94, 0x99, 0x22, 0x24, 0xc0, 0xc5, 0x9c, 0x9d, 0x5a, 0x29, 0xc1, 0xa4, 0xc0, 0xa8, 0xc1, 0x19,
	0x04, 0x62, 0x0a, 0x49, 0x71, 0x71, 0x64, 0xe6, 0x65, 0x96, 0xb8, 0x24, 0x96, 0x24, 0x4a, 0x30,
	0x83, 0xd5, 0xc1, 0xf9, 0x42, 0x12, 0x5c, 0xec, 0x99, 0x79, 0xc9, 0x60, 0x29, 0x16, 0xb0, 0x14,
	0x8c, 0x0b, 0x92, 0xc9, 0x4d, 0xac, 0x00, 0xcb, 0xb0, 0x42, 0x64, 0xa0, 0x5c, 0x25, 0x4f, 0x2e,
	0x11, 0x84, 0xfd, 0x10, 0x77, 0x81, 0x75, 0x18, 0x72, 0xb1, 0x25, 0x83, 0x79, 0x12, 0x8c, 0x0a,
	0xcc, 0x1a, 0xdc, 0x46, 0x92, 0x7a, 0x08, 0x87, 0xeb, 0xa1, 0x38, 0x3a, 0x08, 0xaa, 0x30, 0x89,
	0x0d, 0xec, 0x43, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x49, 0xe4, 0x95, 0xc3, 0xf8, 0x00,
	0x00, 0x00,
}
