/*
* This file generated by Acinconfig tool, don't modify it manually! 
*
* proto content: 
////////////////////////////////////////////////////////////////////////
syntax = "proto3";
package dataConfig;

// key:["id"]
message CfgPlayerAttr{
	int32 id = 1;		//唯一id
	string key = 2;		//系统key
	int32 initData = 3;		//初始值
	int32 incData = 4;		//增量值
	int32 maxData = 5;		//最大值
}

message PlayerAttrConfigData{
	repeated CfgPlayerAttr config = 1;
}

////////////////////////////////////////////////////////////////////////
*/

package dataConfig 

import (
	"github.com/golang/protobuf/proto"
	"io/ioutil"
)

func getCfgPlayerAttrKey(id int32) int64 {
	return int64(id)
}

func GetCfgPlayerAttr(id int32) *CfgPlayerAttr {
	key := getCfgPlayerAttrKey(id)
	if item, ok := MapCfgPlayerAttr[key]; ok {
		return item 
	}
	return nil
}

var MapCfgPlayerAttr map[int64]*CfgPlayerAttr = make(map[int64]*CfgPlayerAttr)

func init() {
	data, err := ioutil.ReadFile("../../slg_game_server/config/dataConfig/CfgPlayerAttr.bytes")
	if err != nil {
		panic("file not exsit! ../../slg_game_server/config/dataConfig/CfgPlayerAttr.bytes")
		return
	}

	cfg := &PlayerAttrConfigData{}
	err = proto.Unmarshal(data, cfg)
	if err != nil {
		panic("proto data unmarshal fail!")
		return 
	}

	for _, item := range cfg.Config {
		key := getCfgPlayerAttrKey(item.Id)
		MapCfgPlayerAttr[key] = item
	}
}